### ISSUE TITLE
Тестовые задачи для летней стажировки JetBrains 2017

### ISSUE THREAD

**Issue by unix-junkie** [unix-junkie/teamcity-autotools-plugin#1]
Решения всех алгоритмических задач (т. е. всех, кроме последней) должны быть выполнены на любом из языков, поддерживаемых _JVM_ (_Java_, _Scala_, _Kotlin_, _Groovy_, _Clojure_ и т. д.) без использования сторонних библиотек (кроме runtime-библиотеки выбранного Вами языка) и собираться любым из стандартных инструментов (_Gradle_, _Maven_, _SBT_, _Leiningen_), т. е. в корневом каталоге каждого решения должен присутствовать соотв. файл для сборки (`pom.xml`, `build.gradle`).

Также должен быть предусмотрен простой запуск решения (напр., в случае _Maven_, посредством `mvn exec:java`).

В качестве альтернативы, решение может быть выполнено на _C_ или _C++_ с использованием одной лишь стандартной библиотеки, при этом обязательно наличие `Makefile`'а или интеграция с любой стандартной системой сборки (_CMake_, _Autotools_, _SCons_). Решение должно собираться _GCC_ и/или _LLVM_.

Решение каждой из алгоритмических задач должно печатать (на стандартный вывод) **только** численный ответ, т. е. вывод должен выглядеть как, напр.,
```
3.1415926
```
а не
```
Pi=3.1415926
```

Код каждого из решений может быть оформлен как закрытый _Git_-репозиторий на [bitbucket.org](https://bitbucket.org/) с правами на чтение для пользователя [bass](https://bitbucket.org/bass/).

# Алгоритмические задачи

1. Сумма последовательности
    > 1<sup>1</sup> + 2<sup>2</sup> + 3<sup>3</sup> + ... + 10<sup>10</sup>

    равна 10405071317. Найдите последние 10 цифр суммы последовательности
    > 1<sup>1</sup> + 2<sup>2</sup> + 3<sup>3</sup> + ... + 1000<sup>1000</sup>

1. Ряд Фибоначчи задаётся рекуррентным соотношением:
    > F<sub>n</sub> = F<sub>n−1</sub> + F<sub>n−2</sub>, где F<sub>1</sub> = 1 и F<sub>2</sub> = 1.

    Следовательно, первыми 12-ю членами ряда будут:
    > F<sub>1</sub> = 1
    > F<sub>2</sub> = 1
    > F<sub>3</sub> = 2
    > F<sub>4</sub> = 3
    > F<sub>5</sub> = 5
    > F<sub>6</sub> = 8
    > F<sub>7</sub> = 13
    > F<sub>8</sub> = 21
    > F<sub>9</sub> = 34
    > F<sub>10</sub> = 55
    > F<sub>11</sub> = 89
    > F<sub>12</sub> = 144

    12-й член ряда, F<sub>12</sub>, &mdash; это первый член, в десятичной записи которого три цифры.

    Каков индекс первого члена ряда Фибоначчи, в десятичной записи которого 1000 цифр?

1. Факториал 10 равен
    > 10! = 10 × 9 × ... × 3 × 2 × 1 = 3628800,

    а сумма цифр десятичной записи числа равна
    > 3 + 6 + 2 + 8 + 8 + 0 + 0 = 27.

    Найдите сумму цифр десятичной записи числа `100!`
1. 2<sup>15</sup> = 32768, а сумма цифр числа равна
    > 3 + 2 + 7 + 6 + 8 = 26.

    Какова сумма цифр десятичной записи числа 2<sup>1000</sup>?
1. Последовательность натуральных чисел задаётся следующими правилами:
    > n → n/2, если n чётно;
    > n → 3n + 1, если n нечётно.

    Используя их и выбирая 13 в качестве первого члена, получаем последовательность:
    > 13 → 40 → 20 → 10 → 5 → 16 → 8 → 4 → 2 → 1

    Видно, что эта последовательность конечна и содержит ровно 10 членов. Хотя это до сих пор и не доказано (см. [гипотеза Коллатца](https://ru.wikipedia.org/wiki/%D0%93%D0%B8%D0%BF%D0%BE%D1%82%D0%B5%D0%B7%D0%B0_%D0%9A%D0%BE%D0%BB%D0%BB%D0%B0%D1%82%D1%86%D0%B0)), предполагается, что, вне зависимости от выбора первого члена, все подобные последовательности конечны и последним своим членом имеют единицу.

    Если потребовать, чтобы первый член последовательности был строго меньше 1000000, то при каком выборе первого члена последовательность будет иметь наибольшую длину?

    **Примечание**: ограничение распространяется _только_ на первый член; значения последующих членов _могут_ превышать один миллион.

# Задачи на владение инструментами

1. Создайте простейший проект на _C_ или _C++_ (_GCC_, _Autotools_) с реализацией native-метода _Java_ посредством _JNI_ (в виде разделяемой библиотеки &mdash; `*.so`).

    Требования:
    * Сценарий `configure` должен находить (если `java` в переменной `PATH` или определена переменная `JAVA_HOME`) хедер `jni.h` и библиотеку `libjvm.so`, создавая `Makefile` с корректными `CFLAGS` и `LDFLAGS`.
    * Сценарий `configure` должен принимать аргумент `--with-java-home=...`, позволяющий указать каталог установки _JDK_ явно.
    * Если установка _JDK_ не обнаружена, сценарий `configure` должен выводить понятное сообщение об ошибке.
    * Реализация native-метода _Java_ должна просто бросать (произвольное, на Ваш выбор) _Java_-исключение с непустым сообщением.
    * Хедер-файл, соответствующий _Java_-классу (`com_example_SomeClass.h`) должен автоматически создаваться из _Java_-класса (утилитой `javah`). Сгенерированный `Makefile` должен содержать необходимые инструкции.

**Comment by Sammers21** [comment]
Алгоритмические задачи нужно считать в лоб?

**Comment by Sammers21** [comment]
Здравствуйте.

[Мой закрытый репозиторий](https://bitbucket.org/Sammers21/teamcity-autotools-plugin) с решениями достпуен Вам с правами на чтение. 

Пожалуйста, дайте мне знать если чего-то не хватает или если что-то нужно переделать. Я с радостью займусь этим. 

Так же, пожалуйста, напишите появился ли у вас доступ к репозиторию и смогли ли вы его посмотреть.

Можете так же писать сюда:
```
    Telegram: telegram.me/Sammers21
    Email: titantins@gmail.com
```

**Comment by lberserq** [comment]
Здравствуйте, Выложено + пошарено.
https://bitbucket.org/lberserq/autotools_task
https://bitbucket.org/lberserq/task1 
https://bitbucket.org/lberserq/task2
https://bitbucket.org/lberserq/task3
https://bitbucket.org/lberserq/task4
https://bitbucket.org/lberserq/task5

**Comment by unix-junkie** [comment]
@lberserq Камиль, спасибо, принято. Я обязательно проверю и отвечу.

**Comment by YorovSobir** [comment]
Добрый вечер.
Выложил все задания с правами чтения для bass.
https://YorovSobir@bitbucket.org/YorovSobir/internship.git

**Comment by PersDep** [comment]
Здравствуйте,

У меня репозитории на GItHub с доступом для unix-junkie, это нормально?
Если нужно, могу залить на Bitbucket.

https://github.com/PersDep/JetBrainsTask1
https://github.com/PersDep/JetBrainsTask2
https://github.com/PersDep/JetBrainsTask3
https://github.com/PersDep/JetBrainsTask4
https://github.com/PersDep/JetBrainsTask5
https://github.com/PersDep/JetBrainsInstrumentTask

Telegram: telegram.me/SBBMos

**Comment by unix-junkie** [comment]
@YorovSobir: Собир, здравствуйте.
Спасибо.
Доступ есть.
Проверю.

**Comment by unix-junkie** [comment]
@PersDep Илья, спасибо, доступ есть.

**Comment by ghost** [comment]
Здравствуйте, выложил с необходимыми правами 
https://bitbucket.org/NikitaBratukhin/task1
https://bitbucket.org/NikitaBratukhin/task2
https://bitbucket.org/NikitaBratukhin/task3
https://bitbucket.org/NikitaBratukhin/task4
https://bitbucket.org/NikitaBratukhin/task5
https://bitbucket.org/NikitaBratukhin/autotools

**Comment by tavplubix** [comment]
Здравствуйте, вот репозитории с решениями
https://bitbucket.org/tavplubix/jb-algorithmical-tasks
https://bitbucket.org/tavplubix/jb-jni-task

**Comment by Naduxa** [comment]
https://bitbucket.org/Naduxa3009/task-autotools

**Comment by evgerher** [comment]
Здравствуйте, с небольшим опозданием
https://bitbucket.org/evgerher/jetbrains

**Comment by evgerher** [comment]
Здравствуйте, с небольшим опозданием
https://bitbucket.org/evgerher/jetbrains

**Comment by unix-junkie** [comment]
Друзья,

спасибо всем вам за участие,
и ждём вас снова в 2018 году.
