### ISSUE TITLE
Test TeamCity TAP Plug-in

### ISSUE THREAD

**Issue by unix-junkie** [unix-junkie/teamcity-autotools-plugin#6]
Test TeamCity [TAP Plug-in](https://github.com/pavelsher/teamcity-tap-parser) against any of the _Autotools_ projects which use _TAP_ for test reporting.

Later, we may (or may not) want to rely on the [tap4j](https://github.com/tupilabs/tap4j) library (available under the MIT license) rather than maintain our custom _TAP_ support.

See also [https://instanttap.appspot.com/](https://instanttap.appspot.com/).

**Comment by Naduxa** [comment]
Fom Automake manual:
TAP, the Test Anything Protocol, is a simple text-based interface between testing modules or programs and a test harness.The tests (also called “TAP producers” in this context) write test results in a simple format on standard output; a test harness (also called “TAP consumer”) will parse and interpret these results, and properly present them to the user, and/or register them for later analysis. 
**The Automake harness will present the results on the console in the usual fashion (see [Testsuite progress on console], page 103), and will use the .trs files (see [Basics of test metadata], page 105) to store the test results and related metadata.**
